import type { Parcel, ShipmentDraft, ShippingQuote } from './types'
export const volumetricWeight = (p: Pick<Parcel, 'length'|'width'|'height'>, divisor = 5000) => p.length * p.width * p.height / divisor
export const chargeableWeight = (p: Parcel, divisor = 5000) => Math.max(p.weight, volumetricWeight(p, divisor))
export const totalChargeableWeight = (parcels: Parcel[], divisor = 5000) => parcels.reduce((sum, p) => sum + chargeableWeight(p, divisor), 0)
export type PricingRule = { percentage?: number; fixed?: number; minimumMargin?: number; minimumPrice?: number; rounding?: number }
export function calculateCustomerPrice(purchase: number, rule: PricingRule) { let value=purchase*(1+(rule.percentage??0)/100)+(rule.fixed??0); value=Math.max(value,purchase+(rule.minimumMargin??0),rule.minimumPrice??0); const increment=rule.rounding??1; return Math.ceil(value/increment)*increment }
const rates=[['UPS','Standard','2–4 business days',105,{percentage:30,minimumMargin:50}],['DHL','Express','1–2 business days',165,{percentage:25,fixed:25,minimumMargin:50}],['FedEx','International Priority','1–3 business days',180,{percentage:30,minimumMargin:50}],['GLS','Parcel','2–5 business days',85,{fixed:40,minimumMargin:50}]] as const
export function mockQuotes(draft: Pick<ShipmentDraft,'destinationCountry'|'parcels'>): ShippingQuote[] { const weight=totalChargeableWeight(draft.parcels); const intl=draft.destinationCountry!=='DK'; return rates.filter((r)=>intl||r[0]==='GLS'||r[0]==='UPS').map(([carrier,service,estimate,base,rule],i)=>{const purchase=base+weight*(intl?12:6);return{id:`quote-${i+1}`,carrier,serviceName:service,productCode:`${carrier.toLowerCase()}-${service.toLowerCase().replaceAll(' ','-')}`,serviceCodes:[],purchasePrice:Math.round(purchase),customerPrice:calculateCustomerPrice(purchase,{...rule,rounding:1}),currency:'DKK',estimatedDelivery:estimate,metadata:{source:'mock',chargeableWeight:weight}}}) }
const EU=new Set(['AT','BE','BG','HR','CY','CZ','DK','EE','FI','FR','DE','GR','HU','IE','IT','LV','LT','LU','MT','NL','PL','PT','RO','SK','SI','ES','SE'])
export const requiresCustoms=(origin:string,destination:string)=>EU.has(origin)!==EU.has(destination)
export const countries=[{code:'DK',name:'Denmark'},{code:'SE',name:'Sweden'},{code:'NO',name:'Norway'},{code:'DE',name:'Germany'},{code:'NL',name:'Netherlands'},{code:'FR',name:'France'},{code:'GB',name:'United Kingdom'},{code:'US',name:'United States'},{code:'CA',name:'Canada'},{code:'AU',name:'Australia'}]
