import type { Parcel, ShipmentDraft, ShippingQuote } from './types'
export const volumetricWeight = (p: Pick<Parcel, 'length'|'width'|'height'>, divisor = 5000) => p.length * p.width * p.height / divisor
export const chargeableWeight = (p: Parcel, divisor = 5000) => Math.max(p.weight, volumetricWeight(p, divisor))
export const totalChargeableWeight = (parcels: Parcel[], divisor = 5000) => parcels.reduce((sum, p) => sum + chargeableWeight(p, divisor), 0)
export type PricingRule = { percentage?: number; fixed?: number; minimumMargin?: number; minimumPrice?: number; rounding?: number }
export function calculateCustomerPrice(purchase: number, rule: PricingRule) { let value=purchase*(1+(rule.percentage??0)/100)+(rule.fixed??0); value=Math.max(value,purchase+(rule.minimumMargin??0),rule.minimumPrice??0); const increment=rule.rounding??1; return Math.ceil(value/increment)*increment }
const rates=[['DAO','Home Delivery','1–2 business days',49,{percentage:25,minimumMargin:30}],['Bring','Parcel','2–4 business days',79,{percentage:28,minimumMargin:35}],['PostNord','MyPack Home','1–3 business days',59,{percentage:25,fixed:10,minimumMargin:30}],['GLS','Parcel Shop','2–5 business days',65,{fixed:30,minimumMargin:30}]] as const
export function mockQuotes(draft: Pick<ShipmentDraft,'destinationCountry'|'parcels'|'carrierName'>): ShippingQuote[] { const weight=totalChargeableWeight(draft.parcels); const intl=draft.destinationCountry!=='DK'; const pool=draft.carrierName?rates.filter((r)=>r[0]===draft.carrierName):rates; return pool.map(([carrier,service,estimate,base,rule])=>{const purchase=base+weight*(intl?12:6);return{id:`quote-${carrier.toLowerCase()}`,carrier,serviceName:service,productCode:`${carrier.toLowerCase()}-${service.toLowerCase().replaceAll(' ','-')}`,serviceCodes:[],purchasePrice:Math.round(purchase),customerPrice:calculateCustomerPrice(purchase,{...rule,rounding:1}),currency:'DKK',estimatedDelivery:estimate,metadata:{source:'mock',chargeableWeight:weight}}}) }
const EU=new Set(['AT','BE','BG','HR','CY','CZ','DK','EE','FI','FR','DE','GR','HU','IE','IT','LV','LT','LU','MT','NL','PL','PT','RO','SK','SI','ES','SE'])
export const requiresCustoms=(origin:string,destination:string)=>EU.has(origin)!==EU.has(destination)
export const countries=[{code:'DK',name:'Denmark'},{code:'SE',name:'Sweden'},{code:'NO',name:'Norway'},{code:'DE',name:'Germany'},{code:'NL',name:'Netherlands'},{code:'FR',name:'France'},{code:'GB',name:'United Kingdom'},{code:'US',name:'United States'},{code:'CA',name:'Canada'},{code:'AU',name:'Australia'}]
