'use client'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, ArrowRight, Check, CircleCheck, Package, Plus, Printer, Trash2 } from 'lucide-react'
import { countries, requiresCustoms } from '@/lib/shipping'
import { boxSizeFor, weightBrackets } from '@/lib/carrierRates'
import { CarrierLogo } from '@/components/carrier-logo'
import { LangContext, DEFAULT_LANG, LANG_STORAGE_KEY, countryName, translations, useLang, useLangCode, type Lang } from '@/lib/i18n'
import type { Address, DeliveryLocation, Parcel, ShipmentDraft, ShippingQuote } from '@/lib/types'

const CARRIERS = [
 {name:'DAO',tagline:'Fast Danish parcel delivery'},
 {name:'Bring',tagline:'Flexible Nordic delivery'},
 {name:'PostNord',tagline:'Nordic parcel specialist'},
 {name:'GLS',tagline:'Affordable European parcels'},
] as const
// Real, carrier-published pickup-point brand names shown on the Service point option. Pricing is
// the same across carriers (Pak & Send's own price list), but the pickup-point branding differs.
const SERVICE_POINT_LABEL: Record<string,string> = { GLS:'GLS PakkeShop', DAO:'daoSHOP', PostNord:'PostNord Service Point', Bring:'Bring pickup point' }
function formatWeight(kg:number){if(kg<=0)return'0';return kg<1?`${Math.round(kg*1000)} g`:`${kg} kg`}
function bracketLabel(brackets:number[],index:number){const lower=index===0?0:brackets[index-1];return`${formatWeight(lower)}–${formatWeight(brackets[index])}`}
function firstParcelSize(location:DeliveryLocation){const brackets=weightBrackets(location);const first=brackets[0];return first!==undefined?{weight:first,...boxSizeFor(first)}:{weight:1,length:30,width:20,height:8}}
const HS_CODE_RE=/^\d{6}(\d{2}){0,3}$/
// Shipmondo decides per-product whether a customs declaration is required (returned as
// `requiresCustoms` in the quote metadata, sourced from the product's `customs_declaration_required`
// field) — that's authoritative and applies to Documents shipments too, not just Goods. The EU/non-EU
// heuristic below is only a best-effort guess used before a quote has come back.
const hasMissingHsCode=(needsCustoms:boolean,draft:ShipmentDraft)=>needsCustoms&&(!draft.items[0]?.hsCode||!HS_CODE_RE.test(draft.items[0].hsCode))

const blankAddress=(country='DK'):Address=>({fullName:'',company:'',address1:'',address2:'',postalCode:'',city:'',country,email:'',phone:''})
const initial:ShipmentDraft={originCountry:'DK',originPostalCode:'',destinationCountry:'SE',destinationPostalCode:'',carrierName:undefined,deliveryLocation:'home',sender:blankAddress(),recipient:blankAddress('SE'),parcels:[{id:'parcel-1',...firstParcelSize('home')}],contentsType:'GOODS',items:[]}
const required=(value:string)=>value.trim().length>1

export function SendWizard(){
 const [lang,setLang]=useState<Lang>(DEFAULT_LANG)
 const tr=translations[lang]
 const [step,setStep]=useState(0),[draft,setDraft]=useState(initial),[quotes,setQuotes]=useState<ShippingQuote[]>([]),[error,setError]=useState(''),[confirmed,setConfirmed]=useState(false),[booking,setBooking]=useState(false),[quoting,setQuoting]=useState(false),[result,setResult]=useState<{reference:string;tracking:string}|null>(null),[customsOverride,setCustomsOverride]=useState<boolean|null>(null)
 useEffect(()=>{const timer=setTimeout(()=>{try{const savedLang=localStorage.getItem(LANG_STORAGE_KEY);if(savedLang==='da'||savedLang==='en')setLang(savedLang)}catch{}try{const saved=localStorage.getItem('pak-send-progress');if(saved)setDraft(d=>({...d,...JSON.parse(saved)}))}catch{}},0);return()=>clearTimeout(timer)},[])
 useEffect(()=>{try{localStorage.setItem(LANG_STORAGE_KEY,lang)}catch{}},[lang])
 useEffect(()=>{localStorage.setItem('pak-send-progress',JSON.stringify({carrierName:draft.carrierName,deliveryLocation:draft.deliveryLocation,originCountry:draft.originCountry,originPostalCode:draft.originPostalCode,destinationCountry:draft.destinationCountry,destinationPostalCode:draft.destinationPostalCode,parcels:draft.parcels}))},[draft.carrierName,draft.deliveryLocation,draft.originCountry,draft.originPostalCode,draft.destinationCountry,draft.destinationPostalCode,draft.parcels])
 const ALL_STEPS=[tr.stepCarrier,tr.stepParcel,tr.stepSender,tr.stepRecipient,tr.stepCustoms,tr.stepReview]
 const selected=quotes.find(q=>q.id===draft.selectedQuoteId)
 const needsCustoms=customsOverride??requiresCustoms(draft.originCountry,draft.destinationCountry)
 const visibleSteps=[0,1,2,3,...(needsCustoms?[4]:[]),5]
 function stepBefore(s:number){const p=s-1;return p===4&&!needsCustoms?3:p}
 function valid(){if(step===1)return draft.parcels.every(p=>[p.weight,p.length,p.width,p.height].every(v=>v>0));if(step===2||step===3){const a=step===2?draft.sender:draft.recipient;return [a.fullName,a.address1,a.postalCode,a.city,a.email,a.phone].every(required)}if(step===4)return required(draft.items[0]?.description??'')&&HS_CODE_RE.test(draft.items[0]?.hsCode??'')&&(draft.items[0]?.unitValue??0)>0;return true}
 async function next(){if(!valid()){setError(tr.fillRequired);return}setError('');if(step===3){setQuoting(true);try{const res=await fetch('/api/quotes',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(draft)});const body=await res.json();if(!res.ok)throw new Error(body.error?.message);const nextQuotes:ShippingQuote[]=body.data;if(!nextQuotes.length){setError(`${draft.carrierName} ${tr.doesNotDeliverSuffix}`);setQuoting(false);return}setQuotes(nextQuotes);setDraft(d=>({...d,selectedQuoteId:nextQuotes[0].id}));const customsRequired=nextQuotes[0].metadata.requiresCustoms;setCustomsOverride(customsRequired??null);setQuoting(false);setStep((customsRequired??requiresCustoms(draft.originCountry,draft.destinationCountry))?4:5)}catch{setError(tr.quoteFetchError);setQuoting(false)}return}setStep(s=>Math.min(s+1,5))}
 function selectCarrier(name:string){setDraft(d=>({...d,carrierName:name}));setError('');setStep(1)}
 function selectDeliveryLocation(location:DeliveryLocation){setDraft(d=>{const brackets=weightBrackets(location);return{...d,deliveryLocation:location,parcels:d.parcels.map(p=>brackets.includes(p.weight)?p:{...p,...firstParcelSize(location)})}})}
 function updateAddress(kind:'sender'|'recipient',key:keyof Address,value:string){setDraft(d=>{const next={...d,[kind]:{...d[kind],[key]:value}};if(kind==='sender'&&key==='country')next.originCountry=value;if(kind==='sender'&&key==='postalCode')next.originPostalCode=value;if(kind==='recipient'&&key==='country')next.destinationCountry=value;if(kind==='recipient'&&key==='postalCode')next.destinationPostalCode=value;return next})}
 function updateCustoms(patch:Partial<ShipmentDraft['items'][number]>){setDraft(d=>{const base=d.items[0]??{id:'customs-item',description:'',quantity:1,unitValue:0,currency:'DKK',weight:d.parcels[0]?.weight??1,originCountry:d.originCountry,hsCode:''};return {...d,items:[{...base,...patch}]}})}
 async function book(){if(!confirmed||!selected||hasMissingHsCode(needsCustoms,draft))return;setBooking(true);setError('');try{const res=await fetch('/api/shipments',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...draft,confirmation:true,idempotencyKey:crypto.randomUUID()})});const body=await res.json();if(!res.ok)throw new Error(body.error?.message);setResult(body.data);localStorage.removeItem('pak-send-progress')}catch{setError(tr.bookingError)}finally{setBooking(false)}}
 const posInVisible=visibleSteps.indexOf(step)
 return <LangContext.Provider value={lang}>{result?<Confirmation result={result} quote={selected!}/>:<div className="wizard-shell">{step===0&&<header className="wizard-header"><div/><div className="lang-switch"><button aria-label="Dansk" className={lang==='da'?'selected':''} onClick={()=>setLang('da')}><img src="/lang/Flag_of_Denmark.svg.webp" alt="Dansk"/></button><button aria-label="English" className={lang==='en'?'selected':''} onClick={()=>setLang('en')}><img src="/lang/Flag_of_the_United_Kingdom_(3-5).svg" alt="English"/></button></div></header>}<div className="progress"><div className="progress-line"><i style={{width:`${posInVisible/(visibleSteps.length-1)*100}%`}}/></div>{visibleSteps.map(i=><button key={i} className={i===step?'active':i<step?'done':''} onClick={()=>i<step&&setStep(i)}><span>{i<step?<Check size={15}/>:visibleSteps.indexOf(i)+1}</span>{ALL_STEPS[i]}</button>)}</div><main className="wizard-main">{step===0&&<CarrierStep draft={draft} onSelect={selectCarrier}/>} {step===1&&<Parcels draft={draft} setDraft={setDraft} onSelectLocation={selectDeliveryLocation}/>} {step===2&&<AddressStep title={tr.senderTitle} value={draft.sender} onChange={(k,v)=>updateAddress('sender',k,v)} minimal/>} {step===3&&<AddressStep title={tr.recipientTitle} value={draft.recipient} onChange={(k,v)=>updateAddress('recipient',k,v)} instructions/>} {step===4&&<Customs item={draft.items[0]} onChange={updateCustoms}/>} {step===5&&<Review draft={draft} quote={selected} needsCustoms={needsCustoms} confirmed={confirmed} setConfirmed={setConfirmed} edit={setStep}/>} {error&&<div className="form-error">{error}</div>}{step>0&&<div className="wizard-actions"><button className="button button-secondary" onClick={()=>setStep(s=>Math.max(stepBefore(s),0))}><ArrowLeft/> {tr.backAction}</button><div/>{step<5?<button className="button button-primary" disabled={quoting} onClick={next}>{quoting?tr.checkingRate:tr.continueAction} <ArrowRight/></button>:<button className="button button-primary" disabled={!confirmed||booking||hasMissingHsCode(needsCustoms,draft)} onClick={book}>{booking?tr.creatingShipment:tr.confirmCreateShipment} <ArrowRight/></button>}</div>}</main></div>}</LangContext.Provider>
}
function Field({label,value,onChange,type='text',optional=false,placeholder}: {label:string;value:string|number;onChange:(v:string)=>void;type?:string;optional?:boolean;placeholder?:string}){const tr=useLang();return <label className="field"><span>{label}{optional&&<small>{tr.optional}</small>}</span><input type={type} value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/></label>}
function Country({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){const lang=useLangCode();return <label className="field"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{countries.map(c=><option value={c.code} key={c.code}>{countryName(c.code,c.name,lang)}</option>)}</select></label>}
function CarrierStep({draft,onSelect}:{draft:ShipmentDraft;onSelect:(name:string)=>void}){const tr=useLang();return <><div className="step-heading"><h1>{tr.carrierHeading}</h1></div><div className="carrier-grid">{CARRIERS.map(c=><button key={c.name} className={draft.carrierName===c.name?'selected':''} onClick={()=>onSelect(c.name)}><CarrierLogo name={c.name}/></button>)}</div></>}
function AddressStep({title,value,onChange,instructions=false,minimal=false}:{title:string;value:Address;onChange:(k:keyof Address,v:string)=>void;instructions?:boolean;minimal?:boolean}){const tr=useLang();return <><div className="step-heading"><h1>{title}</h1></div><section className="form-card wide"><div className="fields two"><Field label={tr.fullName} value={value.fullName} onChange={v=>onChange('fullName',v)}/>{!minimal&&<Field label={tr.company} optional value={value.company??''} onChange={v=>onChange('company',v)}/>}<Field label={tr.addressLine1} value={value.address1} onChange={v=>onChange('address1',v)}/>{!minimal&&<Field label={tr.addressLine2} optional value={value.address2??''} onChange={v=>onChange('address2',v)}/>}<Field label={tr.postalCode} value={value.postalCode} onChange={v=>onChange('postalCode',v)}/><Field label={tr.city} value={value.city} onChange={v=>onChange('city',v)}/><Country label={tr.country} value={value.country} onChange={v=>onChange('country',v)}/>{!minimal&&<Field label={tr.stateRegion} optional value={value.state??''} onChange={v=>onChange('state',v)}/>}<Field label={tr.email} type="email" value={value.email} onChange={v=>onChange('email',v)}/><Field label={tr.mobilePhone} type="tel" value={value.phone} onChange={v=>onChange('phone',v)}/>{instructions&&<Field label={tr.deliveryInstructions} optional value={value.instructions??''} onChange={v=>onChange('instructions',v)}/>}</div></section></>}
function DeliveryLocationPicker({carrierName,value,onSelect}:{carrierName?:string;value:DeliveryLocation;onSelect:(l:DeliveryLocation)=>void}){const tr=useLang();return <div className="choice-grid"><button className={value==='service_point'?'selected':''} onClick={()=>onSelect('service_point')}>{value==='service_point'&&<span className="check-badge"><Check size={14}/></span>}<img src="/servicepoint.png" alt=""/><b>{SERVICE_POINT_LABEL[carrierName??'']??tr.servicePointFallback}</b><small>{tr.servicePointSubtitle}</small></button><button className={value==='home'?'selected':''} onClick={()=>onSelect('home')}>{value==='home'&&<span className="check-badge"><Check size={14}/></span>}<img src="/homedelivery.png" alt=""/><b>{tr.homeDelivery}</b><small>{tr.homeDeliverySubtitle}</small></button></div>}
function Parcels({draft,setDraft,onSelectLocation}:{draft:ShipmentDraft;setDraft:React.Dispatch<React.SetStateAction<ShipmentDraft>>;onSelectLocation:(l:DeliveryLocation)=>void}){const tr=useLang();const brackets=weightBrackets(draft.deliveryLocation);function selectWeight(id:string,maxWeight:number){setDraft(d=>({...d,parcels:d.parcels.map(p=>p.id===id?{...p,weight:maxWeight,...boxSizeFor(maxWeight)}:p)}))}return <><div className="step-heading"><h1>{tr.parcelHeading}</h1></div><section className="form-card wide"><div className="card-label"><b>1</b><span>{tr.chooseDeliveryLabel}</span></div><DeliveryLocationPicker carrierName={draft.carrierName} value={draft.deliveryLocation} onSelect={onSelectLocation}/></section>{draft.parcels.map((p,i)=><section className="form-card wide parcel" key={p.id}><div className="parcel-title"><b><Package/> {tr.parcelLabel} {i+1}</b>{draft.parcels.length>1&&<button onClick={()=>setDraft(d=>({...d,parcels:d.parcels.filter(x=>x.id!==p.id)}))}><Trash2/> {tr.remove}</button>}</div><div className="card-label"><b>2</b><span>{tr.chooseWeightLabel}</span></div><div className="weight-options">{brackets.map((b,idx)=><button key={b} className={p.weight===b?'selected':''} onClick={()=>selectWeight(p.id,b)}><span className="weight-option-text"><b>{bracketLabel(brackets,idx)}</b><small>{tr.upTo} {boxSizeFor(b).length} × {boxSizeFor(b).width} × {boxSizeFor(b).height} cm</small></span><span className="radio">{p.weight===b&&<Check size={15}/>}</span></button>)}</div></section>)}<button className="add-button" onClick={()=>setDraft(d=>({...d,parcels:[...d.parcels,{id:crypto.randomUUID(),...firstParcelSize(d.deliveryLocation)}]}))}><Plus/> {tr.addParcel}</button></>}
function Customs({item,onChange}:{item?:ShipmentDraft['items'][number];onChange:(patch:Partial<ShipmentDraft['items'][number]>)=>void}){const tr=useLang();return <><div className="step-heading"><h1>{tr.customsHeading}</h1><p>{tr.customsSubtitle}</p></div><section className="form-card wide"><div className="fields two"><Field label={tr.contentsDescription} value={item?.description??''} onChange={v=>onChange({description:v})}/><Field label={tr.valueDkk} type="number" value={item?.unitValue??0} onChange={v=>onChange({unitValue:+v})}/><Field label={tr.commodityCode} placeholder="e.g. 610910" value={item?.hsCode??''} onChange={v=>onChange({hsCode:v})}/></div></section></>}
function Review({draft,quote,needsCustoms,confirmed,setConfirmed,edit}:{draft:ShipmentDraft;quote?:ShippingQuote;needsCustoms:boolean;confirmed:boolean;setConfirmed:(v:boolean)=>void;edit:(n:number)=>void}){const tr=useLang();const lang=useLangCode();const missingHsCode=hasMissingHsCode(needsCustoms,draft);return <><div className="step-heading"><h1>{tr.reviewHeading}</h1></div><div className="review-grid"><ReviewCard title={tr.cardCarrier} editLabel={tr.editAction} edit={()=>edit(0)}><b>{draft.carrierName}</b><span>{countryName(draft.originCountry,countries.find(c=>c.code===draft.originCountry)?.name??draft.originCountry,lang)} → {countryName(draft.destinationCountry,countries.find(c=>c.code===draft.destinationCountry)?.name??draft.destinationCountry,lang)}</span></ReviewCard><ReviewCard title={tr.cardParcel} editLabel={tr.editAction} edit={()=>edit(1)}><b>{draft.parcels.length} {tr.parcelLabel}{draft.parcels.length>1?'s':''}</b><span>{draft.parcels.reduce((n,p)=>n+p.weight,0)} {tr.actualWeightSuffix} · {draft.deliveryLocation==='service_point'?(SERVICE_POINT_LABEL[draft.carrierName??'']??tr.servicePointFallback):tr.homeDelivery}</span></ReviewCard><ReviewCard title={tr.cardSender} editLabel={tr.editAction} edit={()=>edit(2)}><b>{draft.sender.fullName}</b><span>{draft.sender.address1}, {draft.sender.postalCode} {draft.sender.city}</span></ReviewCard><ReviewCard title={tr.cardRecipient} editLabel={tr.editAction} edit={()=>edit(3)}><b>{draft.recipient.fullName}</b><span>{draft.recipient.address1}, {draft.recipient.postalCode} {draft.recipient.city}</span></ReviewCard></div><section className="selected-service"><CarrierLogo name={quote?.carrier??''}/><div><b>{quote?.serviceName}</b><small>{quote?.estimatedDelivery}</small></div><strong>{quote?.customerPrice} DKK</strong></section>{missingHsCode&&<div className="notice">{tr.customsRequiresHs}<button onClick={()=>edit(4)}>{tr.addCustomsDetails}</button></div>}<label className="confirm"><input type="checkbox" checked={confirmed} disabled={missingHsCode} onChange={e=>setConfirmed(e.target.checked)}/><span><b>{tr.confirmCorrect}</b><small>{tr.paymentNote}</small></span></label></>}
function ReviewCard({title,editLabel,edit,children}:{title:string;editLabel:string;edit:()=>void;children:React.ReactNode}){return <section className="review-card"><header>{title}<button onClick={edit}>{editLabel}</button></header>{children}</section>}
function Confirmation({result,quote}:{result:{reference:string;tracking:string};quote:ShippingQuote}){const tr=useLang();return <div className="confirmation"><div className="success-icon"><CircleCheck/></div><h1>{tr.allSetHeading}</h1><p>{tr.bookedReady}</p><section><div><small>{tr.reference}</small><b>{result.reference}</b></div><div><small>{tr.trackingNumber}</small><b>{result.tracking}</b></div><div><small>{tr.service}</small><b>{quote.carrier} {quote.serviceName}</b></div><div><small>{tr.total}</small><b>{quote.customerPrice} DKK</b></div></section><div className="confirmation-actions"><button className="button button-primary"><Printer/> {tr.printLabel}</button><Link className="button button-secondary" href="/send">{tr.sendAnother}</Link></div></div>}
