'use client'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, ArrowRight, Check, CircleCheck, Package, Plus, Printer, Trash2 } from 'lucide-react'
import { chargeableWeight, countries, requiresCustoms, volumetricWeight } from '@/lib/shipping'
import type { Address, Parcel, ShipmentDraft, ShipmentItem, ShippingQuote } from '@/lib/types'

const CARRIERS = [
 {name:'DAO',tagline:'Fast Danish parcel delivery'},
 {name:'Bring',tagline:'Flexible Nordic delivery'},
 {name:'PostNord',tagline:'Nordic parcel specialist'},
 {name:'GLS',tagline:'Affordable European parcels'},
] as const
const carrierClass=(name:string)=>`carrier carrier-${name.toLowerCase().replaceAll(' ','-')}`
const hasMissingHsCode=(draft:ShipmentDraft)=>draft.contentsType==='GOODS'&&requiresCustoms(draft.originCountry,draft.destinationCountry)&&draft.items.some(i=>!i.hsCode||!/^\d{6}(\d{2}){0,3}$/.test(i.hsCode))

const blankAddress=(country='DK'):Address=>({fullName:'',company:'',address1:'',address2:'',postalCode:'',city:'',country,email:'',phone:''})
const initial:ShipmentDraft={originCountry:'DK',originPostalCode:'',destinationCountry:'SE',destinationPostalCode:'',carrierName:undefined,sender:blankAddress(),recipient:blankAddress('SE'),parcels:[{id:'parcel-1',weight:1,length:30,width:20,height:15}],contentsType:'DOCUMENTS',items:[]}
const steps=['Carrier','Parcel','Contents','Sender','Recipient','Review']
const required=(value:string)=>value.trim().length>1

export function SendWizard(){
 const [step,setStep]=useState(0),[draft,setDraft]=useState(initial),[quotes,setQuotes]=useState<ShippingQuote[]>([]),[error,setError]=useState(''),[confirmed,setConfirmed]=useState(false),[booking,setBooking]=useState(false),[quoting,setQuoting]=useState(false),[result,setResult]=useState<{reference:string;tracking:string}|null>(null)
 useEffect(()=>{const timer=setTimeout(()=>{try{const saved=localStorage.getItem('pak-send-progress');if(saved)setDraft(d=>({...d,...JSON.parse(saved)}))}catch{}},0);return()=>clearTimeout(timer)},[])
 useEffect(()=>{localStorage.setItem('pak-send-progress',JSON.stringify({carrierName:draft.carrierName,originCountry:draft.originCountry,originPostalCode:draft.originPostalCode,destinationCountry:draft.destinationCountry,destinationPostalCode:draft.destinationPostalCode,parcels:draft.parcels}))},[draft.carrierName,draft.originCountry,draft.originPostalCode,draft.destinationCountry,draft.destinationPostalCode,draft.parcels])
 const selected=quotes.find(q=>q.id===draft.selectedQuoteId)
 function valid(){if(step===0)return Boolean(draft.carrierName);if(step===1)return draft.parcels.every(p=>[p.weight,p.length,p.width,p.height].every(v=>v>0));if(step===2)return draft.contentsType==='DOCUMENTS'||draft.items.length>0;if(step===3||step===4){const a=step===3?draft.sender:draft.recipient;return [a.fullName,a.address1,a.postalCode,a.city,a.email,a.phone].every(required)}return true}
 async function next(){if(!valid()){setError('Please complete the required fields before continuing.');return}setError('');if(step===4){setQuoting(true);try{const res=await fetch('/api/quotes',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(draft)});const body=await res.json();if(!res.ok)throw new Error(body.error?.message);const nextQuotes:ShippingQuote[]=body.data;if(!nextQuotes.length){setError(`${draft.carrierName} doesn't deliver on this route. Please go back and choose a different carrier.`);setQuoting(false);return}setQuotes(nextQuotes);setDraft(d=>({...d,selectedQuoteId:nextQuotes[0].id}))}catch{setError('We could not fetch a shipping rate. Please ask a staff member for assistance.');setQuoting(false);return}setQuoting(false)}setStep(s=>Math.min(s+1,5))}
 function updateAddress(kind:'sender'|'recipient',key:keyof Address,value:string){setDraft(d=>{const next={...d,[kind]:{...d[kind],[key]:value}};if(kind==='sender'&&key==='country')next.originCountry=value;if(kind==='sender'&&key==='postalCode')next.originPostalCode=value;if(kind==='recipient'&&key==='country')next.destinationCountry=value;if(kind==='recipient'&&key==='postalCode')next.destinationPostalCode=value;return next})}
 function updateParcel(id:string,key:keyof Parcel,value:number){setDraft(d=>({...d,parcels:d.parcels.map(p=>p.id===id?{...p,[key]:value}:p)}))}
 async function book(){if(!confirmed||!selected||hasMissingHsCode(draft))return;setBooking(true);setError('');try{const res=await fetch('/api/shipments',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...draft,confirmation:true,idempotencyKey:crypto.randomUUID()})});const body=await res.json();if(!res.ok)throw new Error(body.error?.message);setResult(body.data);localStorage.removeItem('pak-send-progress')}catch{setError("We couldn't create the shipment. Please ask a staff member for assistance.")}finally{setBooking(false)}}
 if(result)return <Confirmation result={result} quote={selected!}/>
 return <div className="wizard-shell"><header className="wizard-header"><Link href="/" className="brand"><span className="brand-mark">P</span>Pak & Send</Link><span className="help">Need help? Ask our staff</span></header><div className="progress"><div className="progress-line"><i style={{width:`${step/5*100}%`}}/></div>{steps.map((s,i)=><button key={s} className={i===step?'active':i<step?'done':''} onClick={()=>i<step&&setStep(i)}><span>{i<step?<Check size={15}/>:i+1}</span>{s}</button>)}</div><main className="wizard-main">{step===0&&<CarrierStep draft={draft} setDraft={setDraft}/>} {step===1&&<Parcels draft={draft} setDraft={setDraft} update={updateParcel}/>} {step===2&&<Contents draft={draft} setDraft={setDraft}/>} {step===3&&<AddressStep title="Who is sending?" subtitle="Enter the sender's contact and pickup details." value={draft.sender} onChange={(k,v)=>updateAddress('sender',k,v)}/>} {step===4&&<AddressStep title="Who is receiving?" subtitle="Enter the recipient's delivery details." value={draft.recipient} onChange={(k,v)=>updateAddress('recipient',k,v)} instructions/>} {step===5&&<Review draft={draft} quote={selected} confirmed={confirmed} setConfirmed={setConfirmed} edit={setStep}/>} {error&&<div className="form-error">{error}</div>}<div className="wizard-actions">{step>0&&<button className="button button-secondary" onClick={()=>setStep(s=>s-1)}><ArrowLeft/> Back</button>}<div/>{step<5?<button className="button button-primary" disabled={quoting} onClick={next}>{quoting?'Checking rate…':'Continue'} <ArrowRight/></button>:<button className="button button-primary" disabled={!confirmed||booking||hasMissingHsCode(draft)} onClick={book}>{booking?'Creating shipment…':'Confirm & create shipment'} <ArrowRight/></button>}</div></main></div>
}
function Field({label,value,onChange,type='text',optional=false,placeholder}: {label:string;value:string|number;onChange:(v:string)=>void;type?:string;optional?:boolean;placeholder?:string}){return <label className="field"><span>{label}{optional&&<small>Optional</small>}</span><input type={type} value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/></label>}
function Country({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="field"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{countries.map(c=><option value={c.code} key={c.code}>{c.name}</option>)}</select></label>}
function CarrierStep({draft,setDraft}:{draft:ShipmentDraft;setDraft:React.Dispatch<React.SetStateAction<ShipmentDraft>>}){return <><div className="step-heading"><span className="step-kicker">Let&apos;s get started</span><h1>Which carrier do you want to use?</h1><p>Choose a shipping partner and we&apos;ll get your parcel&apos;s details next.</p></div><div className="carrier-grid">{CARRIERS.map(c=><button key={c.name} className={draft.carrierName===c.name?'selected':''} onClick={()=>setDraft(d=>({...d,carrierName:c.name}))}><span className={carrierClass(c.name)}>{c.name}</span><b>{c.name}</b><small>{c.tagline}</small></button>)}</div></>}
function AddressStep({title,subtitle,value,onChange,instructions=false}:{title:string;subtitle:string;value:Address;onChange:(k:keyof Address,v:string)=>void;instructions?:boolean}){return <><div className="step-heading"><span className="step-kicker">Contact details</span><h1>{title}</h1><p>{subtitle}</p></div><section className="form-card wide"><div className="fields two"><Field label="Full name" value={value.fullName} onChange={v=>onChange('fullName',v)}/><Field label="Company" optional value={value.company??''} onChange={v=>onChange('company',v)}/><Field label="Address line 1" value={value.address1} onChange={v=>onChange('address1',v)}/><Field label="Address line 2" optional value={value.address2??''} onChange={v=>onChange('address2',v)}/><Field label="Postal code" value={value.postalCode} onChange={v=>onChange('postalCode',v)}/><Field label="City" value={value.city} onChange={v=>onChange('city',v)}/><Country label="Country" value={value.country} onChange={v=>onChange('country',v)}/><Field label="State / region" optional value={value.state??''} onChange={v=>onChange('state',v)}/><Field label="Email" type="email" value={value.email} onChange={v=>onChange('email',v)}/><Field label="Mobile phone" type="tel" value={value.phone} onChange={v=>onChange('phone',v)}/>{instructions&&<Field label="Delivery instructions" optional value={value.instructions??''} onChange={v=>onChange('instructions',v)}/>}</div></section></>}
function Parcels({draft,setDraft,update}:{draft:ShipmentDraft;setDraft:React.Dispatch<React.SetStateAction<ShipmentDraft>>;update:(id:string,k:keyof Parcel,v:number)=>void}){return <><div className="step-heading"><span className="step-kicker">Parcel details</span><h1>What are you sending it in?</h1><p>Add the weight and dimensions for each parcel.</p></div>{draft.parcels.map((p,i)=><section className="form-card wide parcel" key={p.id}><div className="parcel-title"><b><Package/> Parcel {i+1}</b>{draft.parcels.length>1&&<button onClick={()=>setDraft(d=>({...d,parcels:d.parcels.filter(x=>x.id!==p.id)}))}><Trash2/> Remove</button>}</div><div className="fields four"><Field label="Weight (kg)" type="number" value={p.weight} onChange={v=>update(p.id,'weight',+v)}/><Field label="Length (cm)" type="number" value={p.length} onChange={v=>update(p.id,'length',+v)}/><Field label="Width (cm)" type="number" value={p.width} onChange={v=>update(p.id,'width',+v)}/><Field label="Height (cm)" type="number" value={p.height} onChange={v=>update(p.id,'height',+v)}/></div><div className="weight-summary"><span>Actual <b>{p.weight.toFixed(1)} kg</b></span><span>Volumetric <b>{volumetricWeight(p).toFixed(1)} kg</b></span><span>Chargeable <b>{chargeableWeight(p).toFixed(1)} kg</b></span></div></section>)}<button className="add-button" onClick={()=>setDraft(d=>({...d,parcels:[...d.parcels,{id:crypto.randomUUID(),weight:1,length:30,width:20,height:15}]}))}><Plus/> Add another parcel</button></>}
function Contents({draft,setDraft}:{draft:ShipmentDraft;setDraft:React.Dispatch<React.SetStateAction<ShipmentDraft>>}){function add(){setDraft(d=>({...d,items:[...d.items,{id:crypto.randomUUID(),description:'',quantity:1,unitValue:0,currency:'DKK',weight:1,originCountry:'DK'}]}))}function item(id:string,k:keyof ShipmentItem,v:string|number){setDraft(d=>({...d,items:d.items.map(x=>x.id===id?{...x,[k]:v}:x)}))}return <><div className="step-heading"><span className="step-kicker">Shipment contents</span><h1>What are you sending?</h1><p>Accurate details help your shipment move smoothly.</p></div><div className="choice-grid"><button className={draft.contentsType==='DOCUMENTS'?'selected':''} onClick={()=>setDraft(d=>({...d,contentsType:'DOCUMENTS'}))}><span>DOC</span><b>Documents</b><small>Letters, contracts or paperwork</small></button><button className={draft.contentsType==='GOODS'?'selected':''} onClick={()=>setDraft(d=>({...d,contentsType:'GOODS'}))}><Package/><b>Goods</b><small>Products, gifts or personal items</small></button></div>{draft.contentsType==='GOODS'&&<><div className="notice">Add a commodity (HS) code for each item &mdash; it&apos;s required if this route crosses a customs border.</div>{draft.items.map((x,i)=><section className="form-card wide" key={x.id}><div className="parcel-title"><b>Item {i+1}</b><button onClick={()=>setDraft(d=>({...d,items:d.items.filter(y=>y.id!==x.id)}))}><Trash2/> Remove</button></div><div className="fields four"><Field label="Description" value={x.description} onChange={v=>item(x.id,'description',v)}/><Field label="Quantity" type="number" value={x.quantity} onChange={v=>item(x.id,'quantity',+v)}/><Field label="Unit value (DKK)" type="number" value={x.unitValue} onChange={v=>item(x.id,'unitValue',+v)}/><Field label="Weight (kg)" type="number" value={x.weight} onChange={v=>item(x.id,'weight',+v)}/><Field label="HS code" optional placeholder="e.g. 610910" value={x.hsCode??''} onChange={v=>item(x.id,'hsCode',v)}/></div></section>)}<button className="add-button" onClick={add}><Plus/> Add item</button></>}</>}
function Review({draft,quote,confirmed,setConfirmed,edit}:{draft:ShipmentDraft;quote?:ShippingQuote;confirmed:boolean;setConfirmed:(v:boolean)=>void;edit:(n:number)=>void}){const missingHsCode=hasMissingHsCode(draft);return <><div className="step-heading"><span className="step-kicker">Almost there</span><h1>Review your shipment</h1><p>Check the details before creating your shipment.</p></div><div className="review-grid"><ReviewCard title="Carrier" edit={()=>edit(0)}><b>{draft.carrierName}</b><span>{countries.find(c=>c.code===draft.originCountry)?.name} → {countries.find(c=>c.code===draft.destinationCountry)?.name}</span></ReviewCard><ReviewCard title="Parcel" edit={()=>edit(1)}><b>{draft.parcels.length} parcel{draft.parcels.length>1?'s':''}</b><span>{draft.parcels.reduce((n,p)=>n+p.weight,0)} kg actual weight</span></ReviewCard><ReviewCard title="Sender" edit={()=>edit(3)}><b>{draft.sender.fullName}</b><span>{draft.sender.address1}, {draft.sender.postalCode} {draft.sender.city}</span></ReviewCard><ReviewCard title="Recipient" edit={()=>edit(4)}><b>{draft.recipient.fullName}</b><span>{draft.recipient.address1}, {draft.recipient.postalCode} {draft.recipient.city}</span></ReviewCard></div><section className="selected-service"><span className={carrierClass(quote?.carrier??'')}>{quote?.carrier}</span><div><b>{quote?.serviceName}</b><small>{quote?.estimatedDelivery}</small></div><strong>{quote?.customerPrice} DKK</strong></section>{missingHsCode&&<div className="notice">Customs requires a commodity (HS) code for every item on this route.<button onClick={()=>edit(2)}>Add HS codes</button></div>}<label className="confirm"><input type="checkbox" checked={confirmed} disabled={missingHsCode} onChange={e=>setConfirmed(e.target.checked)}/><span><b>I confirm that the information above is correct.</b><small>Payment integration will be added in a future release.</small></span></label></>}
function ReviewCard({title,edit,children}:{title:string;edit:()=>void;children:React.ReactNode}){return <section className="review-card"><header>{title}<button onClick={edit}>Edit</button></header>{children}</section>}
function Confirmation({result,quote}:{result:{reference:string;tracking:string};quote:ShippingQuote}){return <div className="confirmation"><div className="success-icon"><CircleCheck/></div><span className="step-kicker">Shipment created</span><h1>You&apos;re all set.</h1><p>Your shipment has been booked and is ready for its label.</p><section><div><small>Reference</small><b>{result.reference}</b></div><div><small>Tracking number</small><b>{result.tracking}</b></div><div><small>Service</small><b>{quote.carrier} {quote.serviceName}</b></div><div><small>Total</small><b>{quote.customerPrice} DKK</b></div></section><div className="confirmation-actions"><button className="button button-primary"><Printer/> Print label</button><Link className="button button-secondary" href="/send">Send another parcel</Link></div></div>}
