'use client'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, ArrowRight, Check, CircleCheck, Package, Plus, Printer, Trash2 } from 'lucide-react'
import { countries, requiresCustoms } from '@/lib/shipping'
import { CarrierLogo } from '@/components/carrier-logo'
import type { Address, Parcel, ShipmentDraft, ShippingQuote } from '@/lib/types'

const CARRIERS = [
 {name:'DAO',tagline:'Fast Danish parcel delivery'},
 {name:'Bring',tagline:'Flexible Nordic delivery'},
 {name:'PostNord',tagline:'Nordic parcel specialist'},
 {name:'GLS',tagline:'Affordable European parcels'},
] as const
const WEIGHT_BRACKETS = [
 {label:'0–1 kg',weight:1,length:30,width:20,height:8},
 {label:'1–3 kg',weight:3,length:35,width:25,height:15},
 {label:'3–5 kg',weight:5,length:40,width:30,height:20},
 {label:'5–10 kg',weight:10,length:45,width:35,height:25},
] as const
const hasMissingHsCode=(draft:ShipmentDraft)=>draft.contentsType==='GOODS'&&requiresCustoms(draft.originCountry,draft.destinationCountry)&&draft.items.some(i=>!i.hsCode||!/^\d{6}(\d{2}){0,3}$/.test(i.hsCode))

const blankAddress=(country='DK'):Address=>({fullName:'',company:'',address1:'',address2:'',postalCode:'',city:'',country,email:'',phone:''})
const initial:ShipmentDraft={originCountry:'DK',originPostalCode:'',destinationCountry:'SE',destinationPostalCode:'',carrierName:undefined,sender:blankAddress(),recipient:blankAddress('SE'),parcels:[{id:'parcel-1',weight:WEIGHT_BRACKETS[0].weight,length:WEIGHT_BRACKETS[0].length,width:WEIGHT_BRACKETS[0].width,height:WEIGHT_BRACKETS[0].height}],contentsType:'DOCUMENTS',items:[]}
const steps=['Carrier','Contents','Parcel','Sender','Recipient','Review']
const required=(value:string)=>value.trim().length>1

export function SendWizard(){
 const [step,setStep]=useState(0),[draft,setDraft]=useState(initial),[quotes,setQuotes]=useState<ShippingQuote[]>([]),[error,setError]=useState(''),[confirmed,setConfirmed]=useState(false),[booking,setBooking]=useState(false),[quoting,setQuoting]=useState(false),[result,setResult]=useState<{reference:string;tracking:string}|null>(null)
 useEffect(()=>{const timer=setTimeout(()=>{try{const saved=localStorage.getItem('pak-send-progress');if(saved)setDraft(d=>({...d,...JSON.parse(saved)}))}catch{}},0);return()=>clearTimeout(timer)},[])
 useEffect(()=>{localStorage.setItem('pak-send-progress',JSON.stringify({carrierName:draft.carrierName,originCountry:draft.originCountry,originPostalCode:draft.originPostalCode,destinationCountry:draft.destinationCountry,destinationPostalCode:draft.destinationPostalCode,parcels:draft.parcels}))},[draft.carrierName,draft.originCountry,draft.originPostalCode,draft.destinationCountry,draft.destinationPostalCode,draft.parcels])
 const selected=quotes.find(q=>q.id===draft.selectedQuoteId)
 function valid(){if(step===2)return draft.parcels.every(p=>[p.weight,p.length,p.width,p.height].every(v=>v>0));if(step===3||step===4){const a=step===3?draft.sender:draft.recipient;return [a.fullName,a.address1,a.postalCode,a.city,a.email,a.phone].every(required)}return true}
 async function next(){if(!valid()){setError('Please complete the required fields before continuing.');return}setError('');if(step===4){setQuoting(true);try{const res=await fetch('/api/quotes',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(draft)});const body=await res.json();if(!res.ok)throw new Error(body.error?.message);const nextQuotes:ShippingQuote[]=body.data;if(!nextQuotes.length){setError(`${draft.carrierName} doesn't deliver on this route. Please go back and choose a different carrier.`);setQuoting(false);return}setQuotes(nextQuotes);setDraft(d=>({...d,selectedQuoteId:nextQuotes[0].id}))}catch{setError('We could not fetch a shipping rate. Please ask a staff member for assistance.');setQuoting(false);return}setQuoting(false)}setStep(s=>Math.min(s+1,5))}
 function selectCarrier(name:string){setDraft(d=>({...d,carrierName:name}));setError('');setStep(1)}
 function selectContents(type:'DOCUMENTS'|'GOODS'){setDraft(d=>({...d,contentsType:type}));setError('');setStep(2)}
 function updateAddress(kind:'sender'|'recipient',key:keyof Address,value:string){setDraft(d=>{const next={...d,[kind]:{...d[kind],[key]:value}};if(kind==='sender'&&key==='country')next.originCountry=value;if(kind==='sender'&&key==='postalCode')next.originPostalCode=value;if(kind==='recipient'&&key==='country')next.destinationCountry=value;if(kind==='recipient'&&key==='postalCode')next.destinationPostalCode=value;return next})}
 async function book(){if(!confirmed||!selected||hasMissingHsCode(draft))return;setBooking(true);setError('');try{const res=await fetch('/api/shipments',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...draft,confirmation:true,idempotencyKey:crypto.randomUUID()})});const body=await res.json();if(!res.ok)throw new Error(body.error?.message);setResult(body.data);localStorage.removeItem('pak-send-progress')}catch{setError("We couldn't create the shipment. Please ask a staff member for assistance.")}finally{setBooking(false)}}
 if(result)return <Confirmation result={result} quote={selected!}/>
 return <div className="wizard-shell"><header className="wizard-header"><Link href="/" className="brand"><span className="brand-mark">P</span>Pak & Send</Link><div className="header-links"><span className="help">Need help? Ask our staff</span><Link href="/admin" className="staff-link">Staff login</Link></div></header><div className="progress"><div className="progress-line"><i style={{width:`${step/5*100}%`}}/></div>{steps.map((s,i)=><button key={s} className={i===step?'active':i<step?'done':''} onClick={()=>i<step&&setStep(i)}><span>{i<step?<Check size={15}/>:i+1}</span>{s}</button>)}</div><main className="wizard-main">{step===0&&<CarrierStep draft={draft} onSelect={selectCarrier}/>} {step===1&&<Contents draft={draft} onSelect={selectContents}/>} {step===2&&<Parcels draft={draft} setDraft={setDraft}/>} {step===3&&<AddressStep title="Who is sending?" subtitle="Enter the sender's contact and pickup details." value={draft.sender} onChange={(k,v)=>updateAddress('sender',k,v)} minimal/>} {step===4&&<AddressStep title="Who is receiving?" subtitle="Enter the recipient's delivery details." value={draft.recipient} onChange={(k,v)=>updateAddress('recipient',k,v)} instructions/>} {step===5&&<Review draft={draft} quote={selected} confirmed={confirmed} setConfirmed={setConfirmed} edit={setStep}/>} {error&&<div className="form-error">{error}</div>}{step>0&&<div className="wizard-actions"><button className="button button-secondary" onClick={()=>setStep(s=>s-1)}><ArrowLeft/> Back</button><div/>{step===1?null:step<5?<button className="button button-primary" disabled={quoting} onClick={next}>{quoting?'Checking rate…':'Continue'} <ArrowRight/></button>:<button className="button button-primary" disabled={!confirmed||booking||hasMissingHsCode(draft)} onClick={book}>{booking?'Creating shipment…':'Confirm & create shipment'} <ArrowRight/></button>}</div>}</main></div>
}
function Field({label,value,onChange,type='text',optional=false,placeholder}: {label:string;value:string|number;onChange:(v:string)=>void;type?:string;optional?:boolean;placeholder?:string}){return <label className="field"><span>{label}{optional&&<small>Optional</small>}</span><input type={type} value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/></label>}
function Country({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="field"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{countries.map(c=><option value={c.code} key={c.code}>{c.name}</option>)}</select></label>}
function CarrierStep({draft,onSelect}:{draft:ShipmentDraft;onSelect:(name:string)=>void}){return <><div className="step-heading"><span className="step-kicker">Let&apos;s get started</span><h1>Which carrier do you want to use?</h1><p>Choose a shipping partner and we&apos;ll get your parcel&apos;s details next.</p></div><div className="carrier-grid">{CARRIERS.map(c=><button key={c.name} className={draft.carrierName===c.name?'selected':''} onClick={()=>onSelect(c.name)}><CarrierLogo name={c.name}/></button>)}</div></>}
function AddressStep({title,subtitle,value,onChange,instructions=false,minimal=false}:{title:string;subtitle:string;value:Address;onChange:(k:keyof Address,v:string)=>void;instructions?:boolean;minimal?:boolean}){return <><div className="step-heading"><span className="step-kicker">Contact details</span><h1>{title}</h1><p>{subtitle}</p></div><section className="form-card wide"><div className="fields two"><Field label="Full name" value={value.fullName} onChange={v=>onChange('fullName',v)}/>{!minimal&&<Field label="Company" optional value={value.company??''} onChange={v=>onChange('company',v)}/>}<Field label="Address line 1" value={value.address1} onChange={v=>onChange('address1',v)}/>{!minimal&&<Field label="Address line 2" optional value={value.address2??''} onChange={v=>onChange('address2',v)}/>}<Field label="Postal code" value={value.postalCode} onChange={v=>onChange('postalCode',v)}/><Field label="City" value={value.city} onChange={v=>onChange('city',v)}/><Country label="Country" value={value.country} onChange={v=>onChange('country',v)}/>{!minimal&&<Field label="State / region" optional value={value.state??''} onChange={v=>onChange('state',v)}/>}<Field label="Email" type="email" value={value.email} onChange={v=>onChange('email',v)}/><Field label="Mobile phone" type="tel" value={value.phone} onChange={v=>onChange('phone',v)}/>{instructions&&<Field label="Delivery instructions" optional value={value.instructions??''} onChange={v=>onChange('instructions',v)}/>}</div></section></>}
function Parcels({draft,setDraft}:{draft:ShipmentDraft;setDraft:React.Dispatch<React.SetStateAction<ShipmentDraft>>}){function selectWeight(id:string,b:typeof WEIGHT_BRACKETS[number]){setDraft(d=>({...d,parcels:d.parcels.map(p=>p.id===id?{...p,weight:b.weight,length:b.length,width:b.width,height:b.height}:p)}))}return <><div className="step-heading"><span className="step-kicker">Parcel details</span><h1>What are you sending it in?</h1></div>{draft.parcels.map((p,i)=>{const bracket=WEIGHT_BRACKETS.find(b=>b.weight===p.weight)??WEIGHT_BRACKETS[0];return <section className="form-card wide parcel" key={p.id}><div className="parcel-title"><b><Package/> Parcel {i+1}</b>{draft.parcels.length>1&&<button onClick={()=>setDraft(d=>({...d,parcels:d.parcels.filter(x=>x.id!==p.id)}))}><Trash2/> Remove</button>}</div><div className="weight-options">{WEIGHT_BRACKETS.map(b=><button key={b.label} className={p.weight===b.weight?'selected':''} onClick={()=>selectWeight(p.id,b)}>{b.label}<span className="radio">{p.weight===b.weight&&<Check size={15}/>}</span></button>)}</div><details className="size-disclosure"><summary>Show allowed package size</summary><p>Up to {bracket.length} × {bracket.width} × {bracket.height} cm</p></details></section>})}<button className="add-button" onClick={()=>setDraft(d=>({...d,parcels:[...d.parcels,{id:crypto.randomUUID(),weight:WEIGHT_BRACKETS[0].weight,length:WEIGHT_BRACKETS[0].length,width:WEIGHT_BRACKETS[0].width,height:WEIGHT_BRACKETS[0].height}]}))}><Plus/> Add another parcel</button></>}
function Contents({draft,onSelect}:{draft:ShipmentDraft;onSelect:(type:'DOCUMENTS'|'GOODS')=>void}){return <><div className="step-heading"><h1>What are you sending?</h1></div><div className="choice-grid"><button className={draft.contentsType==='DOCUMENTS'?'selected':''} onClick={()=>onSelect('DOCUMENTS')}><img src="/items/documents.png" alt=""/><b>Documents</b></button><button className={draft.contentsType==='GOODS'?'selected':''} onClick={()=>onSelect('GOODS')}><img src="/items/box.png" alt=""/><b>Box</b></button></div></>}
function Review({draft,quote,confirmed,setConfirmed,edit}:{draft:ShipmentDraft;quote?:ShippingQuote;confirmed:boolean;setConfirmed:(v:boolean)=>void;edit:(n:number)=>void}){const missingHsCode=hasMissingHsCode(draft);return <><div className="step-heading"><span className="step-kicker">Almost there</span><h1>Review your shipment</h1><p>Check the details before creating your shipment.</p></div><div className="review-grid"><ReviewCard title="Carrier" edit={()=>edit(0)}><b>{draft.carrierName}</b><span>{countries.find(c=>c.code===draft.originCountry)?.name} → {countries.find(c=>c.code===draft.destinationCountry)?.name}</span></ReviewCard><ReviewCard title="Parcel" edit={()=>edit(2)}><b>{draft.parcels.length} parcel{draft.parcels.length>1?'s':''}</b><span>{draft.parcels.reduce((n,p)=>n+p.weight,0)} kg actual weight</span></ReviewCard><ReviewCard title="Sender" edit={()=>edit(3)}><b>{draft.sender.fullName}</b><span>{draft.sender.address1}, {draft.sender.postalCode} {draft.sender.city}</span></ReviewCard><ReviewCard title="Recipient" edit={()=>edit(4)}><b>{draft.recipient.fullName}</b><span>{draft.recipient.address1}, {draft.recipient.postalCode} {draft.recipient.city}</span></ReviewCard></div><section className="selected-service"><CarrierLogo name={quote?.carrier??''}/><div><b>{quote?.serviceName}</b><small>{quote?.estimatedDelivery}</small></div><strong>{quote?.customerPrice} DKK</strong></section>{missingHsCode&&<div className="notice">Customs requires a commodity (HS) code for every item on this route.<button onClick={()=>edit(1)}>Add HS codes</button></div>}<label className="confirm"><input type="checkbox" checked={confirmed} disabled={missingHsCode} onChange={e=>setConfirmed(e.target.checked)}/><span><b>I confirm that the information above is correct.</b><small>Payment integration will be added in a future release.</small></span></label></>}
function ReviewCard({title,edit,children}:{title:string;edit:()=>void;children:React.ReactNode}){return <section className="review-card"><header>{title}<button onClick={edit}>Edit</button></header>{children}</section>}
function Confirmation({result,quote}:{result:{reference:string;tracking:string};quote:ShippingQuote}){return <div className="confirmation"><div className="success-icon"><CircleCheck/></div><span className="step-kicker">Shipment created</span><h1>You&apos;re all set.</h1><p>Your shipment has been booked and is ready for its label.</p><section><div><small>Reference</small><b>{result.reference}</b></div><div><small>Tracking number</small><b>{result.tracking}</b></div><div><small>Service</small><b>{quote.carrier} {quote.serviceName}</b></div><div><small>Total</small><b>{quote.customerPrice} DKK</b></div></section><div className="confirmation-actions"><button className="button button-primary"><Printer/> Print label</button><Link className="button button-secondary" href="/send">Send another parcel</Link></div></div>}
